name = "akile-monitor"
main = "src/index.ts"
compatibility_date = "2026-05-03"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true


[[kv_namespaces]]
binding = "KV"

[[d1_databases]]
binding = "DB"
database_name = "akile-monitor-db"

[triggers]
crons = ["*/5 * * * *"] # Every 5 minutes

[vars]
ADMIN_PASSWORD = "admin888"
MAX_PRICE = "20"
MARKET_MONITOR_ENABLED = "true"
AKILE_EMAIL = "318182456@qq.com"
AKILE_PASSWORD = "wal116266321"
AKILE_TOTP_SECRET = "FQJTZASON4AM7ALN4RD5FGBHBSR27DML"