import { LineMeta } from "./types";

export const LINE_META: Record<string, LineMeta> = {
  "JPIIJ": {
    name: "JPIIJ",
    area: "日本 (Japan)",
    emoji: "🇯🇵",
    tags: ["日本直连", "联通神线"],
    stability: "良好",
    stabilityClass: "status-good",
    desc: "日本IIJ线路，三网回程走IIJ优化直连（对联通网络最为友好，电信/移动次之）。",
    pros: "延迟低（江浙沪一般在35-50ms），对联通宽带用户体验极佳，价格公道且带宽充裕。",
    cons: "电信晚高峰期间可能因骨干网拥堵导致延迟抖动及部分丢包现象。",
    nightStatus: "晚高峰（20:00 - 23:00）会有约10%左右的偶发丢包，整体不掉线，联通用户基本无感。",
    nightClass: "",
    telecom: "★★★☆☆",
    unicom: "★★★★★",
    mobile: "★★★★☆",
    label: "日本IIJ直连",
    hint: "联通神线，电信晚高峰微丢包，不掉线",
    color: "#60a5fa"
  },
  "HKS": {
    name: "HKS",
    area: "中国香港 (Hong Kong)",
    emoji: "🇨🇳",
    tags: ["香港标准", "大带宽落地"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "香港Standard线路，通常为国际BGP互联，不承诺对国内方向直连优化。",
    pros: "价格极低，香港原生/解锁IP，国际方向互联极佳，大带宽，非常适合做流媒体落地机。",
    cons: "回国线路未优化，电信绕路严重延迟极高，移动/联通网络也可能绕路。",
    nightStatus: "晚高峰直连回国丢包严重，极易卡顿、降速。虽不会掉线，但必须搭配国内中转/拉跨使用。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★★☆☆",
    label: "香港国际BGP",
    hint: "大带宽落地，直连丢包严重，建议中转",
    color: "#fbbf24"
  },
  "UKLITE": {
    name: "UKLite",
    area: "英国 (United Kingdom)",
    emoji: "🇬🇧",
    tags: ["欧洲落地", "廉价大带宽"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "英国Lite系列，纯国际BGP线路，无回国优化，物理距离遥远。",
    pros: "价格便宜，提供英国本土IP，解锁英国流媒体及各种欧洲本地服务，带宽超大。",
    cons: "国内直连延迟通常在260-350ms+，晚高峰直连丢包非常高。",
    nightStatus: "晚上直连极其卡顿，丢包率可能高达30%以上。适合配合中转落地使用，直连极易连接超时。",
    nightClass: "danger",
    telecom: "★☆☆☆☆",
    unicom: "★☆☆☆☆",
    mobile: "★★☆☆☆",
    label: "英国国际BGP",
    hint: "欧洲落地，晚上直连极其卡顿，需中转",
    color: "#f87171"
  },
  "LAX4837": {
    name: "LAX4837",
    area: "美国洛杉矶 (Los Angeles)",
    emoji: "🇺🇸",
    tags: ["联通回国优化", "性价比神线"],
    stability: "极佳",
    stabilityClass: "status-excellent",
    desc: "美西洛杉矶机房，回程强制三网走联通 AS4837 优化线路直连回国。",
    pros: "三网直连延迟相对稳定（140-180ms），晚高峰回国带宽吞吐强悍，性价比奇高，适合建站及日常使用。",
    cons: "在晚高峰骨干网极度拥堵时，电信和移动用户的延迟会有小幅升高或抖动。",
    nightStatus: "晚上表现稳定，极少掉线。晚高峰会有极轻微延迟抖动，但基本不影响日常使用和速度体验。",
    nightClass: "",
    telecom: "★★★★☆",
    unicom: "★★★★★",
    mobile: "★★★★☆",
    label: "联通4837直连",
    hint: "三网回程直连，晚上稳定不掉线",
    color: "#34d399"
  },
  "TWLITE": {
    name: "TWLite",
    area: "中国台湾 (Taiwan)",
    emoji: "🇨🇳",
    tags: ["台湾解锁", "看剧落地"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "台湾Lite轻量系列，主要使用台湾本土BGP或HiNet等国际网络，无大陆直连优化。",
    pros: "台湾IP解锁神机，完美解锁巴哈姆特动画疯、Netflix台区等台湾流媒体。",
    cons: "国内直连极其绕路（常见绕香港、日本甚至美国），延迟通常在180-250ms+。",
    nightStatus: "晚高峰期间直连丢包非常严重，速度断崖式下跌，虽然很少彻底断网掉线，但直连使用极卡，强烈建议搭配中转。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★☆☆☆",
    label: "台湾国际BGP",
    hint: "解锁神机，晚上直连极卡，建议中转",
    color: "#fbbf24"
  },
  "HINET NAT": {
    name: "HINET NAT",
    area: "中国台湾 (Taiwan)",
    emoji: "🇨🇳",
    tags: ["台湾Hinet", "动态NAT", "流媒体解锁强"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "台湾Hinet动态NAT共享IP节点（通常提供端口映射 and 动态DDNS）。",
    pros: "台湾本土原生IP，流媒体解锁能力强，适合作为台湾本土应用或流媒体落地。",
    cons: "共享端口/IP，不适合需要固定端口和公网IP的建站；国内直连绕路且高延迟。",
    nightStatus: "晚高峰直连受限于骨干网 and 海缆，丢包率非常高（延迟大幅飙升并可能卡顿），极少彻底中断掉线，但强烈推荐搭配中转拉跨使用。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★☆☆☆",
    label: "台湾Hinet NAT",
    hint: "动态IP共享端口，流媒体解锁强，直连极卡建议中转",
    color: "#fbbf24"
  },
  "HKLITE": {
    name: "HKLite",
    area: "中国香港 (Hong Kong)",
    emoji: "🇨🇳",
    tags: ["超低价格", "纯落地机"],
    stability: "较差",
    stabilityClass: "status-poor",
    desc: "香港Lite轻量版，纯国际BGP网络（NTT/Cogent/PCCW等混合），无任何直连优化。",
    pros: "极具竞争力的低廉价格，大带宽，常用于解锁港区流媒体及作为国际数据节点。",
    cons: "国内直连几乎全部绕路（如绕美/绕日），延迟常常达到200ms以上甚至更高。",
    nightStatus: "晚上直连由于国际出口 and 绕路拥堵，会有严重的丢包 and 极高延迟（丢包率达30%-50%），几乎无法直接连通，不推荐直连。",
    nightClass: "danger",
    telecom: "★☆☆☆☆",
    unicom: "★☆☆☆☆",
    mobile: "★★☆☆☆",
    label: "香港国际BGP",
    hint: "大带宽纯落地，晚上直连严重丢包需中转",
    color: "#f87171"
  },
  "NL BGP": {
    name: "NL BGP",
    area: "荷兰 (Netherlands)",
    emoji: "🇳🇱",
    tags: ["欧洲BGP", "抗投诉/大流量"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "荷兰BGP大带宽线路，未作国内回程直连优化，距离中国较远。",
    pros: "价格便宜，对欧洲本地网络互联好，适合BT/PT下载及欧洲本土流媒体落地或特定抗投诉业务。",
    cons: "延迟高达260-320ms，国内方向直接连接性能一般。",
    nightStatus: "晚高峰时受限于海缆拥堵，容易出现较大的丢包和降速，偶尔会有短暂连不上情况，直连不稳。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★☆☆☆",
    label: "荷兰国际BGP",
    hint: "欧洲落地，晚上直连极不稳易瞬断",
    color: "#fbbf24"
  },
  "JPHYPER": {
    name: "JPHyper",
    area: "日本 (Japan)",
    emoji: "🇯🇵",
    tags: ["高性能日本", "日区解锁"],
    stability: "良好",
    stabilityClass: "status-good",
    desc: "日本Hyper系列，主打高性能或更充沛的日本BGP带宽（部分路由可能包含IIJ/KB/SB优化）。",
    pros: "机器硬件性能较好，国际互联极强，解锁日区流媒体（Netflix/木偶/Niconico）稳定。",
    cons: "不承诺长期的国内直连，路由可能随着上游网络调整而变化。",
    nightStatus: "晚上直连稳定性较好，偶尔会有轻微的晚高峰波动或少许丢包，通常不会掉线，配合中转极香。",
    nightClass: "",
    telecom: "★★★☆☆",
    unicom: "★★★★☆",
    mobile: "★★★★☆",
    label: "日本BGP",
    hint: "高性能日区解锁，晚高峰偶有微丢包不掉线",
    color: "#60a5fa"
  },
  "HKL-TW": {
    name: "HKL-TW",
    area: "香港-台湾 (HK to TW)",
    emoji: "🌐",
    tags: ["港台互拉", "极低延迟互联"],
    stability: "良好",
    stabilityClass: "status-good",
    desc: "香港到台湾方向的传输或对拉线路，专为港台两地内网/互联数据流设计。",
    pros: "香港与台湾两地之间的互联延迟极低（通常仅10-25ms左右），特别适合把流量从香港拉往台湾落地使用。",
    cons: "回国方向的网络仍然等同于普通的香港Lite，直连表现同样差强人意。",
    nightStatus: "晚上港台之间互拉稳定性极佳，不会掉线；但如果国内直接连接该节点，晚上会有高丢包 and 高延迟。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★★☆☆",
    label: "港台优化互拉",
    hint: "港台互连极稳，晚上直连回国丢包严重",
    color: "#fbbf24"
  },
  "IT BGP": {
    name: "IT BGP",
    area: "意大利 (Italy)",
    emoji: "🇮🇹",
    tags: ["意大利BGP", "极速欧洲"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "意大利BGP网络，主打国际大带宽，未对国内回程进行特流优化。",
    pros: "适合做欧洲意大利特定落地业务、小语种外贸及欧洲本土代理使用，价格低廉。",
    cons: "国内直连延迟高，绕行较远。",
    nightStatus: "晚高峰容易随欧洲至亚洲骨干光缆拥堵而丢包，直连表现较差，偶尔会出现连接超时或短暂无法连接，建站不宜直连。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★☆☆☆☆",
    mobile: "★★☆☆☆",
    label: "意大利BGP",
    hint: "海外落地，晚高峰丢包高，直连不宜",
    color: "#fbbf24"
  },
  "HKBASE": {
    name: "HKBase",
    area: "中国香港 (Hong Kong)",
    emoji: "🇨🇳",
    tags: ["直连基础版", "性价比均衡"],
    stability: "良好",
    stabilityClass: "status-good",
    desc: "香港基础直连网络，包含了比Lite系列更好的三网直连路由（部分包含CMI/移动直连优化）。",
    pros: "延迟相对较低，价格适中，不经过中转也能获得相对可以接受的直连体验。",
    cons: "晚高峰期间电信用户可能会有间歇性拥堵，总体稳定度低于高端Pro系列。",
    nightStatus: "晚上表现较稳，极少掉线。晚高峰会有10%以内的轻微丢包，日常浏览及看视频能基本保持连通。",
    nightClass: "",
    telecom: "★★★☆☆",
    unicom: "★★★★☆",
    mobile: "★★★★☆",
    label: "香港直连基础版",
    hint: "较稳，晚高峰电信轻微丢包，极少掉线",
    color: "#60a5fa"
  },
  "HKPRO": {
    name: "HKPro",
    area: "中国香港 (Hong Kong)",
    emoji: "🇨🇳",
    tags: ["高端直连", "低延迟建站首选"],
    stability: "极佳",
    stabilityClass: "status-excellent",
    desc: "香港专业高端直连线路，通常接入 CN2 GIA / 联通9929 / 移动CMI高端直连通道。",
    pros: "三网均走顶级优化直连，延迟极低（江浙粤约8-35ms），晚高峰拥堵期依旧丝滑，极其稳定，建站与游戏极佳。",
    cons: "价格昂贵，且商家给的带宽通常较小（例如10-50M），流量相对较少。",
    nightStatus: "全天候极其稳定，晚上也绝对不会掉线，丢包率趋近于0%，即使在深夜黄金时段依然速度拉满。",
    nightClass: "",
    telecom: "★★★★★",
    unicom: "★★★★★",
    mobile: "★★★★★",
    label: "三网高端直连",
    hint: "CN2 GIA/9929/CMI，晚上极其稳定不掉线",
    color: "#34d399"
  },
  "LAX静态住宅": {
    name: "LAX静态住宅",
    area: "美国洛杉矶 (Los Angeles)",
    emoji: "🇺🇸",
    tags: ["住宅IP", "流媒体解锁", "外贸跨境"],
    stability: "极佳",
    stabilityClass: "status-excellent",
    desc: "美西洛杉矶机房静态住宅IP线路，专门针对流媒体全解锁及外贸跨境电商等强风控场景。",
    pros: "纯正静态住宅IP（ISP类型），不易被各大流媒体及风控平台（如TikTok, Netflix, ChatGPT）标记封禁，网络稳定性强。",
    cons: "价格比一般机房BGP套餐高得多，带宽资源通常较为有限，不适合大流量BT下载。",
    nightStatus: "晚高峰稳定性极高，三网延迟相对平稳，几乎没有丢包，正常情况下绝不掉线。",
    nightClass: "",
    telecom: "★★★★☆",
    unicom: "★★★★★",
    mobile: "★★★★☆",
    label: "洛杉矶静态住宅IP",
    hint: "双ISP静态住宅IP，跨境与流媒体解锁神机，晚高峰极稳",
    color: "#ec4899"
  },
  "DEBGP": {
    name: "DEBGP",
    area: "德国 (Germany)",
    emoji: "🇩🇪",
    tags: ["德国BGP", "欧洲落地"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "德国法兰克福BGP大带宽线路，未针对国内回程进行特流优化，物理距离较远。",
    pros: "价格便宜，国际及欧洲本地互联极佳，提供欧洲大带宽与大流量落地。",
    cons: "直连中国延迟较高（通常在180-260ms），晚高峰直连丢包多。",
    nightStatus: "晚高峰容易随欧洲至亚洲骨干光缆拥堵而丢包，直连表现较差，推荐使用国内中转拉跨落地。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★☆☆☆",
    label: "德国国际BGP",
    hint: "欧洲落地，晚高峰直连丢包较高，建议中转",
    color: "#fbbf24"
  },
  "LAX LITE": {
    name: "LAX Lite",
    area: "美国洛杉矶 (Los Angeles)",
    emoji: "🇺🇸",
    tags: ["廉价美西", "大带宽落地"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "洛杉矶Lite轻量系列，纯美西BGP网络，不提供国内回程直连优化。",
    pros: "价格极具性价比，大带宽，适合作为美区解锁/流媒体落地，或配合国内中转使用。",
    cons: "直连延迟高，且在晚高峰由于骨干网拥堵，丢包率会明显飙升。",
    nightStatus: "晚高峰期间直连容易受到严重影响，丢包率高，推荐通过中转拉跨使用，直连使用体验不佳。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★☆☆☆",
    label: "美西国际BGP",
    hint: "大带宽落地，晚高峰直连丢包高，建议中转",
    color: "#fbbf24"
  },
  "MOLITE": {
    name: "MOLite",
    area: "中国澳门 (Macau)",
    emoji: "🇲🇴",
    tags: ["澳门落地", "流媒体解锁"],
    stability: "一般",
    stabilityClass: "status-warning",
    desc: "澳门Lite轻量线路，使用澳门本土BGP网络，对国内无特殊直连优化。",
    pros: "提供澳门本地原生IP，支持解锁澳门本地流媒体及各种特有网络服务。",
    cons: "直连路由不稳定，经常绕行香港，且晚高峰期间延迟与丢包较多。",
    nightStatus: "晚高峰直连会有明显抖动与丢包，整体运行尚可，建议配合中转使用以获得低延迟体验。",
    nightClass: "warn",
    telecom: "★☆☆☆☆",
    unicom: "★★☆☆☆",
    mobile: "★★★☆☆",
    label: "澳门国际BGP",
    hint: "澳门原生落地，直连延迟较高，建议中转",
    color: "#fbbf24"
  },
  "DEBGP LITE": {
    name: "DEBGP Lite",
    area: "德国 (Germany)",
    emoji: "🇩🇪",
    tags: ["极廉欧洲", "大带宽纯落地"],
    stability: "较差",
    stabilityClass: "status-poor",
    desc: "德国轻量BGP线路，无回国优化，物理距离长且带宽拥堵较为严重。",
    pros: "价格极其廉价，大带宽，适合欧洲本地轻量业务或极低预算 of 海外落地。",
    cons: "直连中国丢包率极高，延迟常年在200ms以上，极易连接超时。",
    nightStatus: "晚高峰直连非常卡顿，丢包率可达30%以上，甚至可能短暂失联，直连基本不可用，必须中转。",
    nightClass: "danger",
    telecom: "★☆☆☆☆",
    unicom: "★☆☆☆☆",
    mobile: "★★☆☆☆",
    label: "德国轻量BGP",
    hint: "欧洲极廉落地，晚上直连卡死，必须中转",
    color: "#f87171"
  },
  "LAX4837ISP": {
    name: "LAX4837ISP",
    area: "美国洛杉矶 (Los Angeles)",
    emoji: "🇺🇸",
    tags: ["双ISP住宅", "AS4837回国", "解锁神机"],
    stability: "极佳",
    stabilityClass: "status-excellent",
    desc: "洛杉矶双ISP住宅属性线路，且回程强制三网走联通 AS4837 优化链路。",
    pros: "兼具双ISP（模拟住宅网络）的极强流媒体/电商风控解锁能力，以及AS4837优化回国路线的低延迟与高吞吐速度。",
    cons: "相较普通美西AS4837机型价格较贵，流量资源较为珍贵。",
    nightStatus: "全天稳定性优秀，晚高峰期间会有极轻微延迟抖动，但速度与连通率依旧极高，直连无压力。",
    nightClass: "",
    telecom: "★★★★☆",
    unicom: "★★★★★",
    mobile: "★★★★☆",
    label: "美西双ISP 4837",
    hint: "双ISP住宅属性 + AS4837直连，流媒体全解锁，晚上极稳",
    color: "#34d399"
  }
};
